### ISSUE TITLE
Wrong sunset time for San Francisco

### ISSUE THREAD

**Issue by apuder** [mikereedell/sunrisesunsetlib-java#17]
[edited]
Location location = new Location("37.739558", "-122.479749");
SunriseSunsetCalculator calculator = new SunriseSunsetCalculator(location, "America/Los_Angeles");
Calendar sunset = calculator.getCivilSunsetCalendarForDate(Calendar.getInstance());

For date 5/3 it reports 20:31. Actual sunset is 20:03.

**Comment by MenoData** [comment]
Late answer: You should select the method `getOfficialSunsetCalendarForDate()` instead. Then you will get close agreement with your expectation. That said, you had by mistake calculated civil twilight, not sunset. I suggest to close this issue.
