### ISSUE TITLE
null result from calculations

### ISSUE THREAD

**Issue by pawelrokosznyvimana** [mikereedell/sunrisesunsetlib-java#34]
Hi
After executing such code for Warsaw/Poland
```
        Calendar calendar = Calendar.getInstance();
        SunriseSunsetCalculator calc = new SunriseSunsetCalculator(new Location(52.2297700,  21.0117800), "Poland");
        calc.getAstronomicalSunriseCalendarForDate(calendar);
```
I get null result. As I checked, it's returned by

computeSolarEventTme in:
```
        if ((cosineSunLocalHour.doubleValue() < -1.0) || (cosineSunLocalHour.doubleValue() > 1.0)) {
            return null;
        }
```

**Comment by forrestguice** [comment]
not really a bug. null is returned because there is no rise/set for astronomical twilight (on this particular day). In other words it does not get darker than astronomical twilight. 

https://www.timeanddate.com/astronomy/poland/warsaw

**Comment by pawelrokosznyvimana** [comment]
It could be more information about it or maybe more descriptive way of presenting it since null does not tell anything but your're right and thanks for explaining what went wrong.
Cloing issue.
